const aeronavCharts = require('./index.js')

const logCharts = (charts) => Object.values(charts).map(chart => console.log(chart))

aeronavCharts.vfr.sectionals().then(logCharts)
// aeronavCharts.vfr.terminalArea().then(logCharts)
// aeronavCharts.vfr.helicopter().then(logCharts)
// aeronavCharts.vfr.grandCanyon().then(logCharts)
// aeronavCharts.vfr.planning().then(logCharts)
// aeronavCharts.vfr.caribbean().then(logCharts)
// aeronavCharts.vfr.all().then(logCharts)

// aeronavCharts.ifr.enrouteLow().then(logCharts)
// aeronavCharts.ifr.enrouteHigh().then(logCharts)
// aeronavCharts.ifr.enrouteLowHighAlaska().then(logCharts)
// aeronavCharts.ifr.enrouteArea().then(logCharts)
// aeronavCharts.ifr.enrouteHawaiiPacific().then(logCharts)
// aeronavCharts.ifr.planning().then(logCharts)
// aeronavCharts.ifr.gulf().then(logCharts)
// aeronavCharts.ifr.all().then(logCharts)
